.TH "/home/connor/csc230/tools/pub/cunit/src/new_file.c" 3 "Mon Apr 29 2013" "Version 0.6" "CUnit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/connor/csc230/tools/pub/cunit/src/new_file.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVERSION\fP   0\&.5"
.br
.ti -1c
.RI "#define \fBCOMMENT_BLOCK_WIDTH\fP   56"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBgen_test\fP = 0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COMMENT_BLOCK_WIDTH   56"

.PP
Definition at line 38 of file new_file\&.c\&.
.SS "#define VERSION   0\&.5"

.PP
Definition at line 37 of file new_file\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.PP
Definition at line 47 of file new_file\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "int gen_test = 0"

.PP
Definition at line 45 of file new_file\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CUnit from the source code\&.
