.TH "/home/connor/csc230/tools/pub/cunit/src/write_test.c" 3 "Mon Apr 29 2013" "Version 0.6" "CUnit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/connor/csc230/tools/pub/cunit/src/write_test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVERSION\fP   0\&.5"
.br
.ti -1c
.RI "#define \fBCOMMENT_BLOCK_WIDTH\fP   56"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBwrite_testfile\fP (char *filename)"
.br
.ti -1c
.RI "void \fBwrite_makefile\fP (char **filelist)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COMMENT_BLOCK_WIDTH   56"

.PP
Definition at line 37 of file write_test\&.c\&.
.SS "#define VERSION   0\&.5"

.PP
Definition at line 36 of file write_test\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.PP
Definition at line 266 of file write_test\&.c\&.
.SS "void write_makefile (char **filelist)"

.PP
Definition at line 83 of file write_test\&.c\&.
.SS "void write_testfile (char *filename)"

.PP
Definition at line 40 of file write_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CUnit from the source code\&.
